# Generated by Django 2.0.3 on 2018-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliexpresscookie',
            name='state',
            field=models.CharField(default='ok', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_lucky',
            field=models.BooleanField(default=False),
        ),
    ]
